# collectionbuilder-gh
# a Jekyll Digital Collection Generator
# designed for GitHub Pages

# Site settings

# title of site appears in banner
title: Mining History in Idaho
# tagline appears in banner
tagline: a digital exhibit created by the University of Idaho's History 404 class, Fall 2018
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Explore photographs and papers that document the history of mining in northern Idaho"
# keywords appear in meta tags
keywords: "university of idaho, digital history, mining"
# creator of the digital collection, to appear in meta tags
author: evanwill
# creator contact email for meta tags
email: ewilliamson@uidaho.edu
# collection project date, when did you publish this
collection-date: "2018"

# url is your gh-pages base, following the pattern: username.github.io
url: https://uidaholib.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /hist404-fall2018
# repository is the github repository's full url
repository: https://github.com/uidaholib/hist404-fall2018

# Theme Options
# navbar text color
# Choose from "navbar-light" for use with light background colors, or "navbar-dark" for dark background colors
navbar-color: navbar-dark
# navbar background color
# Choose from bg-primary, bg-secondary, bg-success, bg-danger, bg-warning, bg-info, bg-light, bg-dark, bg-white
navbar-background: bg-secondary
# theme with Bootswatch (https://github.com/thomaspark/bootswatch)
# Choose from: cerulean; cosmo; cyborg; darkly; flatly; journal; litera; lumen; lux; materia; minty; pulse; sandstone; simplex; sketchy; slate; solar; spacelab; superhero; united; yeti 
bootswatch: # leave blank or comment out for plain bootstrap

# google services [optional!]
# leave these blank or comment out to NOT include google code
google-tracking-id: "UA-76328753-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# build settings
permalink: pretty

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
